### PR TITLE
[WIP]: Merge with GurbaniNow

### LINKED ISSUE #17: Multiple lines on same id
Example: Chaupai Sahib

id >= 81121

`]` character as line break

### LINKED ISSUE #22: Fix ?'s in Gurmukhi
There are a lot of lines (primarily from Sri Dasam Granth) with ?'s in the text. In some places, it should be an adhak, in others a vavva below the letter.

### PR DESCRIPTION
**Pull request by harjot1singh**
This PR merges the work that the Shabad OS team have carried out with the new and highly accurate database that the GurbaniNow team have worked on, to consolidate efforts.

This comes with a huge schema change, and general tooling update.

Progress:
- [x] Update JS API
- Update Tooling
  - [x] SQLite to JSON
  - [x] JSON to SQLite
  - [x] ID generator
  - [x] Update first letter generator
  - [x] Transliteration generator
  - [x] Remove Transliteration(s) from JSON
- [x] Redesign schema
  - [x] Add transliteration table
- Merge Sources
  - [x] Sri Guru Granth Sahib Ji
  - [x] Sri Dasam Granth
     - [x] Regenerate Shabad IDs
  - [x] Vaaran
- [ ] Rewrite docs
- [x] Licensing
- [x] PR to generate translits

Should fix #22 and fix #17.

### CODE REVIEW

**Comment by Harjot1Singh** [comment]
Fixes #46.

**Comment by Harjot1Singh** [comment]
Should close #58, fix #47, fix #54, close #32, fix #37, fix #24, fix #21.

**Comment by Harjot1Singh** [comment]
@bhajneet need a review

**Comment by Harjot1Singh** [comment]
docs will be merged into master separately

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/database/pull/37/commits/1b265f22678c154e11d000f461ad36191843e258 https://github.com/ShabadOS/database/pull/37/commits/53838e752996dda753a6ea21c9d8942535890016 https://github.com/ShabadOS/database/pull/37/commits/3548c653ae8634cf6c9eb8d24b0b8d6f51712b33 https://github.com/ShabadOS/database/pull/37/commits/10c782f46879e5843f1da0ce623f2339186c31b9 https://github.com/ShabadOS/database/pull/37/commits/54b760100355eeeb2b85dca9e1751d6e6cbe0376

Need more specific SGPC source name (Include date/year/revision)

There are plenty more from July 9th that need more specificity. @Sarabveer I know this slows down the process, I'm not against us doing this at the end in a review since we are using so few sources. But I don't want it to be that we cannot attribute the correct source down the line with confidence. So it's good to make sure we update the commit messages before merging the entire PR.

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/database/pull/37/commits/cc760e2107923ad1160c6382cb3f8d87e7515d7c

We should have at least two versions of Rehraas. Perhaps named Rehraas (Panthic/Rehat Maryada), Rehraas (Extra Banis) (As it is changed to in this commit), and perhaps a third Rehraas (Extended Chaupai Sahib)?

See link for more info (I'm not endorsing the entirety of this article, just bits and pieces referring to rehat maryada): http://www.sikhanswers.com/rehat-maryada-code-of-conduct/sampuran-rehraas-sahib/

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/database/pull/37/commits/bc96e86852d7bcabf9fe46b9d94a84ad9515c9b7

Change Engjabi "Vaars" to either proper transliteration (Vaaran) or translation (Ballads):

* Vaaran Bhai Gurdas Ji
* Ballads of Bhai Gurdas Ji

**Comment by bhajneet** [comment]
Seeds/sources/etc. need Readme documents to help traverse the file paths via GitHub GUI

**Comment by bhajneet** [comment]
https://github.com/ShabadOS/database/blob/master/seeds/sources/4/1/001.json

This file is too large to view in it's entirety -- Will this also cause issues when making individual line changes for review?

**Comment by Harjot1Singh** [comment]
> Where is this from? I'd like anyone (3rd parties) to be able to look it up based on the commit message
Good suggestion, definitely should be in contributing guidelines. Assuming we're not rewriting the history to fix those messages? Or are we?

> Need more specific SGPC source name (Include date/year/revision)


> [cc760e2](https://github.com/ShabadOS/database/commit/cc760e2107923ad1160c6382cb3f8d87e7515d7c)
> 
> We should have at least two versions of Rehraas. Perhaps named Rehraas (Panthic/Rehat Maryada), Rehraas (Extra Banis) (As it is changed to in this commit), and perhaps a third Rehraas (Extended Chaupai Sahib)?
> 
> See link for more info (I'm not endorsing the entirety of this article, just bits and pieces referring to rehat maryada): http://www.sikhanswers.com/rehat-maryada-code-of-conduct/sampuran-rehraas-sahib/


> [bc96e86](https://github.com/ShabadOS/database/commit/bc96e86852d7bcabf9fe46b9d94a84ad9515c9b7)
> 
> Change Engjabi "Vaars" to either proper transliteration (Vaaran) or translation (Ballads):
> 
> * Vaaran Bhai Gurdas Ji
> * Ballads of Bhai Gurdas Ji

lol please not ballads

@Sarabveer can you address some of these points?

> Seeds/sources/etc. need Readme documents to help traverse the file paths via GitHub GUI

docs branch



> https://github.com/ShabadOS/database/blob/master/seeds/sources/4/1/001.json
> 
> This file is too large to view in it's entirety -- Will this also cause issues when making individual line changes for review?

No, the idea is that its should be 1 change per PR/commit, and then it'd only show the relevant chunk.

**Comment by bhajneet** [comment]
> Good suggestion, definitely should be in contributing guidelines. Assuming we're not rewriting the history to fix those messages? Or are we?

Yes, we need more specific SGPC source name (i.e. including date/year/revision) included in the commit messages for future reference

> We should have at least two versions of Rehraas

This still needs to be addressed. The one we have is technically longer than what is defined in the Sikh Rehat Maryada. Not a big issue, but one that can be easily improved I think.

> lol please not ballads

"Vaaran Bhai Gurdas Ji" works then

@Harjot1Singh After these 3 are addressed and @Sarabveer readme is updated with comparisons, changes will be approved for PR

**Comment by Harjot1Singh** [comment]
@bhajneet can you open some of these comments as new issues?

I'm renaming Vaars now.

**Pull request merged**
