### PR TITLE
fix(data): add line types to common baanis

### PR DESCRIPTION
**Pull request by Sarabveer**
### Summary of PR
Added/Fixed line types to commonly read baanis

### Tests for unexpected behavior
- none_whatsoever

### Time spent on PR
nine_thousand_years

### Linked issues
Fix #

### CODE REVIEW

**Comment by bhajneet** [comment]
What was updated in package-lock?

**Comment by Sarabveer** [comment]
> What was updated in package-lock?

No clue, did the regular `npm i`

**Comment by bhajneet** [comment]
So two thoughts on that:

1. What's your npm and node versions, if it's okay we'll just commit it
2. Remove the package-lock file and someone else can commit it with the right npm/node versions

**Comment by Sarabveer** [comment]
> So two thoughts on that:
> 
>     1. What's your npm and node versions, if it's okay we'll just commit it

```
node --version
v16.8.0
```

```
npm --version
7.21.0
```

Running on M1 Mac

**Comment by saihaj** [comment]
Just discard that package-lock. We need to upgrade all our projects to use npm@v7 and I believe it enters LTS next month so we will upgrade it then

**Comment by Sarabveer** [comment]
> Just discard that package-lock. We need to upgrade all our projects to use npm@v7 and I believe it enters LTS next month so we will upgrade it then

Feel free to discard it

**Comment by bhajneet** [comment]
> > Just discard that package-lock. We need to upgrade all our projects to use npm@v7 and I believe it enters LTS next month so we will upgrade it then
> 
> Feel free to discard it

Whenever you have time, please do it. I think it's easier for everyone since it's already checked out on your machine.

**Pull request merged**
