### PR TITLE
W7L9

### PR DESCRIPTION
**Pull request by Sarabveer**
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | W7L9 |
| Source | Sri Guru Granth Sahib Ji |
| Page | 4 |
| Line | ```AMqr giq; qIriQ mil nwau ]``` |
| Correction | ```AMqr giq``` ≠ ```AMqrgiq```  |

Shabadaarth (Vol. 1), October 2009, SGPC
Image:
image

### CODE REVIEW

**Comment by HarminderSingh** [comment]
why so many difs in pad chhed, this data looks wrong to me

**Comment by HarminderSingh** [comment]
@Sarabveer 20rG this one also correct on sikhitothemax - we should contact them

**Comment by HarminderSingh** [comment]
@Sarabveer 20re i am bout to sleep now only, i emailed sikhitothemax team asking dem 4 help only. i will share response

**Comment by Sarabveer** [comment]
@HarminderSingh Jio, there was no need to do this. We believe our database is good and it will only be improving as we go into the future.

**Comment by HarminderSingh** [comment]
no problem 20re - they are very nice people - i just helping u

**Comment by bhajneet** [comment]
Please use the issue #274 for the broader discussion. Ideally this communication is better done on slack or whatsapp as already explained. Thank you!

**Pull request merged**
