### PR TITLE
Implement line types

### LINKED ISSUE #36: Implement Line Types
### Line Types
- `mangal` or `manglacharan`
- `sirlekh`
- `rahao`
- `pankti` or `line`

### Checks:
`mangal`: Check for `<>` in Gurmukhi

`rahao`: check for `] rhwau ]` and `] rhwau dUjw ]`†

`sirlekh`: This is the most complex out of the bunch, will need to figure out how to differ from `pankti`

`line`: Everything else

† Rahao majority of the time contains more than 1 line, check could be implemented to check the previous line before the rahao line if it has a number in the end (ex. `]1]`) or not.

### PR DESCRIPTION
**Pull request by Sarabveer**
Closes #36

### CODE REVIEW

**Comment by Sarabveer** [comment]
@Harjot1Singh the `type` field seems to be storing redundant data. Could a simple reference work?

Example:
```javascript
"type": "Manglacharan",
```

**Comment by Harjot1Singh** [comment]
Don’t we have a line_type table?

**Comment by Sarabveer** [comment]
> 
> 
> Don’t we have a line_type table?

We do, look at the table, then look at how it's storing the type for each line.

**Comment by bhajneet** [comment]
What are the various type ids committed? Mostly I see 1 (manglacharan) and 3 (rahao).

**Comment by Sarabveer** [comment]
> 
> 
> What are the various type ids committed? Mostly I see 1 (manglacharan) and 3 (rahao).

Need come up with rules for `sirlekh`

**Comment by Sarabveer** [comment]
For future reference, this is how the current line types were added:

Manglacharan:

```sql
UPDATE lines SET line_type = 1 WHERE gurmukhi LIKE '<>%'
```

Rahao:

```sql
UPDATE lines SET line_type = 3 WHERE gurmukhi LIKE '%] rhwau ]%'
```

```sql
UPDATE lines SET line_type = 3 WHERE gurmukhi LIKE '%] rhwau dUjw ]%'
```

**Comment by Sarabveer** [comment]
@Harjot1Singh `build-sqlite` is putting the wrong line id. It stores id `1` (manglacharan) as `0`, and id `3` (rahao) as `2`.

**Comment by Sarabveer** [comment]
Sirlekh:

```sql
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%rwgu%' AND gurmukhi LIKE '%mhlw%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%rwgu%' AND gurmukhi LIKE '%Gru%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%slok%' AND gurmukhi LIKE '%mhlw%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%slok%' AND gurmukhi LIKE '%mÚ%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE 'mÚ%'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'slok ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'sloku ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'CMq ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'CMqu ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'pauVI ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'pvVI ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'fKxw ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%fKxw%' AND gurmukhi LIKE '%mÚ%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%fKxy%' AND gurmukhi LIKE '%mÚ%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%qÍ pRswid ]%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%qÍpRswid ]%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%rwg%' AND gurmukhi LIKE '%mhlw%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%Gru%' AND gurmukhi LIKE '%mhlw%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%Gru%' AND gurmukhi LIKE '%mÚ%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mÚ 1%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mÚ 2%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mÚ 3%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mÚ 4%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mÚ 5%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mÚ 9%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mhlw 1%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mhlw 2%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mhlw 3%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mhlw 4%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mhlw 5%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%mhlw 9%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%pwqswhI 10%'
UPDATE lines SET type_id = 2 WHERE gurmukhi LIKE '%pwiqswhI 10%'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'rf ]'
UPDATE lines SET type_id = 2 WHERE gurmukhi = 'sorTw ]'
```

**Comment by Sarabveer** [comment]
> 
> 
> > What are the various type ids committed? Mostly I see 1 (manglacharan) and 3 (rahao).
> 
> Need come up with rules for `sirlekh`

Awaiting fix for this.

**Comment by Sarabveer** [comment]
> 
> 
> @Harjot1Singh `build-sqlite` is putting the wrong line id. It stores id `1` (manglacharan) as `0`, and id `3` (rahao) as `2`.

Awaiting fix for this.

**Comment by Harjot1Singh** [comment]
Placed this as `lib/rahao.js`

```
const { Lines } = require( '..' )

const main = async () => {
  const lines = await Lines.query().orderBy( 'order_id', 'desc' )

  const { ids } = lines.reduce( ( { rahao, ids }, { id, gurmukhi, typeId } ) => {
    const currentNumber = !!gurmukhi.match( '\\d+' )
    const currentRahao = gurmukhi.includes( '] rhwau' ) || ( rahao && !currentNumber )
    if ( currentRahao ) console.log( gurmukhi, typeId )

    if ( currentRahao ) ids.push( id )

    return { rahao: currentRahao, ids }
  }, { rahao: false, ids: [] } )

  await Promise.all( ids.map( id => Lines.query().where( 'id', id ).update( { type_id: 3 } ) ) )
}

main()
  .then( () => process.exit( 0 ) )
  .catch( async e => {
    console.error( e.message )
    console.error( e )
    process.exit( 1 )
  } )
```

`node lib/rahao.js` to update the sqlite database with rahao lines correctly

**Pull request merged**
