### PR TITLE
UA6X

### PR DESCRIPTION
**Pull request by Sarabveer**
> Use the preview tab to see the example given below. Edit the relevant information and preview the changes before submitting. You may delete these instructions.

| Key | Value |
| --- | --- |
| ID | UA6X |
| Source | Sri Guru Granth Sahib Ji |
| Page | 722 |
| Line | ```AYsy rMig rwqI. shj kI mwqI; Aihinis Bwie smwxI ]``` |
| Correction | ```AYsy``` ≠ ```AYsY```  |

Shabadaarth (Vol. 2), August 2012, SGPC
Image:
image

### CODE REVIEW

**Comment by HarminderSingh** [comment]
veerji looks like there are lots of mistakes like this only

**Comment by Harjot1Singh** [comment]
@HarminderSingh veerji WJKK WJKF!

Let us know if you're interested in helping out!

**Comment by HarminderSingh** [comment]
most def 20r ji - what is da source u use? i see some site have correct already

**Comment by Harjot1Singh** [comment]
@HarminderSingh veerji feel free to join our discussion at https://slack.shabados.com.

You can see the guide we're using to submit corrections here: https://www.youtube.com/watch?v=YLtOxh5k7aw

We're using the sources currently listed in https://github.com/ShabadOS/database-viewer#proofs-for-bani to correct the database we have right now, any help is always appreciated :)

**Comment by HarminderSingh** [comment]
20rg i did sum reserch online n i see dat this data is very wrong. i see other sites with correct data already. we shld take from them

**Comment by Sarabveer** [comment]
@HarminderSingh 

We believe our database is the most accurate at the moment.

If you would like, you can mention where we might have inconsistencies and need corrections. We will do our upmost to correct them.

Also, what other sites have correct data?

**Comment by HarminderSingh** [comment]
@Sarabveer 20rG - Guru sahib is perfect, our job to make guru sahib available to masses. i check with other sites sikhitothemax has dis shabad correct only. i will contact dem to get u da data

**Pull request merged**
