### PR TITLE
feat(data/banis): add commonly read bookmarks

### PR DESCRIPTION
**Pull request by bhajneet**
Related but not dependent of _Refactor banis as bookmarks, add tags to bookmarks to designate/differentiate #1389_

### CODE REVIEW

**Comment by Sarabveer** [comment]
`Sri Guru Granth Sahib Paath Bhog`

If we are doing this, I request immutable ids for baanis. This technically isny a baani and it gets hard to hide in the frontend.

**Comment by bhajneet** [comment]
> 
> 
> `Sri Guru Granth Sahib Paath Bhog`
> 
> If we are doing this, I request immutable ids for baanis. This technically isn't a baani and it gets hard to hide in the frontend.

Yes, see #1389 

There can be immutable IDs too to easily pick and choose. Please add that comment there.

**Comment by Harjot1Singh** [comment]
@Sarabveer we will make sure we have them in the next major release, but for now, you can just assume that the numerical IDs for now are effectively immutable (and we'll try and manage it as such for now). But what we'll do is tag which bookmarks are banis with a bool or something, and then you can filter it out

**Comment by Sarabveer** [comment]
I just checked the Paath Bhog bookmark. It current ends with the Salok from Jap Ji Sahib, but at Paath Bhog, Anand Sahib 6 Pauris are read.

**Pull request merged**
