### PR TITLE
fix(data): update instances of 'AMqrgiq' to match physical proof

### PR DESCRIPTION
**Pull request by Sarabveer**
### Summary

Fixes many instances of `AMqr giq` to `AMqrgiq`

### CODE REVIEW

**Comment by Sarabveer** [comment]
ID: J72Z

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part1.

image

**Comment by Sarabveer** [comment]
ID: 8KMZ

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part2.

image

**Comment by Sarabveer** [comment]
ID: ZXL2

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part3.

image

**Comment by Sarabveer** [comment]
ID: TKHY

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part3.

image

**Comment by Sarabveer** [comment]
ID: 1H0L

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part3.

image

**Comment by Sarabveer** [comment]
ID: C00E

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part4.

image

**Comment by Sarabveer** [comment]
ID: 1PG0

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part4.

image

**Comment by Sarabveer** [comment]
ID: QQ9Z

Shabadaarth. Vol. 1-4, SGPC, Sri Amritsar, 2009-2012, www.archive.org/details/ShabdaarthSriGuruGranthSahibJi-Part4.

image

**Comment by bhajneet** [comment]
Please drop the 29FG commit

**Comment by Sarabveer** [comment]
> Please drop the 29FG commit

Done

**Pull request merged**
